### PR TITLE
[#86] Support old option response formats

### PR DESCRIPTION
**Pull request by jonase**

### CODE REVIEW

**Comment by iperdomo** [comment]
@jonase right now we're not doing anything with the _code_ but if Flow introduced it is because some people actually use it? Why don't we normalize to `code` = `text` for those answers that *don't* have `code` ? -- Just a question

**Comment by jonase** [comment]
> Why don't we normalize to code = text for those answers that don't have code

We could do that if we want to. @muloem what's your thoughts?

OTOH, it could also makes sense to leave off non-results instead instead of making up values. @muloem does all new flow option responses contain the `code` part? Even if no code was specified in the question definition?

**Comment by muloem** [comment]
My preference is to leave the code as null or not even include it in cases where its not supplied. The option responses contain code only if its been set in the question definition. Otherwise it (response) will come with text only. e.g.

```
[{"text":"4"},{"text":"5"},{"text":"test","isOther":true}]
```

**Comment by muloem** [comment]
The difficulty was to ensure that the `isOther` is set correctly with the old format.  It required having the question definition so as to match the list of responses against the list of options.

**Review by muloem — APPROVED** [review]

**Pull request merged**
